# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/ffcv.transforms.ipynb.

# %% auto 0
__all__ = ['RandomResizedCrop', 'RandomHorizontalFlip', 'RandomTranslate', 'Cutout', 'RandomBrightness', 'RandomContrast',
           'RandomSaturation', 'Poison', 'ReplaceLabel', 'Squeeze']

# %% ../../nbs/ffcv.transforms.ipynb 1
from ffcv.transforms.cutout import Cutout
from ffcv.transforms.flip import RandomHorizontalFlip
from ffcv.transforms.random_resized_crop import RandomResizedCrop
from ffcv.transforms.translate import RandomTranslate
from ffcv.transforms.color_jitter import RandomBrightness, RandomContrast, RandomSaturation
from ffcv.transforms.poisoning import Poison
from ffcv.transforms.replace_label import ReplaceLabel
from ffcv.transforms.common import Squeeze

# %% ../../nbs/ffcv.transforms.ipynb 2
_all_ = ['RandomResizedCrop', 'RandomHorizontalFlip', 'RandomTranslate', 'Cutout',
         'RandomBrightness', 'RandomContrast', 'RandomSaturation', 'Poison', 'ReplaceLabel', 'Squeeze']
