# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TensorImage.resize": "augment.tensor_item_tfm.ipynb",
         "TensorMask.resize": "augment.tensor_item_tfm.ipynb",
         "TensorImage.crop_pad": "augment.tensor_item_tfm.ipynb",
         "TensorMask.crop_pad": "augment.tensor_item_tfm.ipynb",
         "RandomCrop.encodes": "augment.tensor_item_tfm.ipynb",
         "CropPad.encodes": "augment.tensor_item_tfm.ipynb",
         "Resize.encodes": "augment.tensor_item_tfm.ipynb",
         "RandomResizedCrop.encodes": "augment.tensor_item_tfm.ipynb",
         "RatioResize.encodes": "augment.tensor_item_tfm.ipynb",
         "CutMixUp": "callback.cutmixup.ipynb",
         "CutMixUpAugment": "callback.cutmixup.ipynb",
         "LRFinder": "callback.lr_finder.ipynb",
         "Learner.lr_find": "callback.lr_finder.ipynb",
         "Callback.__call__": "callback.simpleprofiler.ipynb",
         "Learner.all_batches": "callback.simpleprofiler.ipynb",
         "Learner.show_training_loop": "callback.simpleprofiler.ipynb",
         "SimpleProfilerPostCallback": "callback.simpleprofiler.ipynb",
         "SimpleProfilerCallback": "callback.simpleprofiler.ipynb",
         "Learner.profile": "callback.simpleprofiler.ipynb",
         "is_listish": "schedulers.fit_flat_varied.ipynb",
         "Learner.fit_flat_varied": "schedulers.fit_flat_varied.ipynb",
         "WandbCallback.before_fit": "utils.simpleprofiler_wandb.ipynb",
         "WandbCallback.after_fit": "utils.simpleprofiler_wandb.ipynb"}

modules = ["augment/tensor_item_tfm.py",
           "callback/cutmixup.py",
           "callback/lr_finder.py",
           "callback/simpleprofiler.py",
           "schedulers/fit_flat_varied.py",
           "utils/simpleprofiler_wandb.py"]

doc_url = "https://warner-benjamin.github.io/fastai_snippets/"

git_url = "https://github.com/warner-benjamin/fastai_snippets/tree/main/"

def custom_doc_links(name): return None
